
name: Update stats

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  update-readme: 
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN}}
          USERNAME: amchuz
   stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Let the magic happen
        uses: actions/setup-node@v1
        with:
          node-version: 12.15.0

      - run: npm i
      - run: node .   
        
            

      - name: Add to git repo
        run: |
           git add .
           git config --global user.name "Amchuz"
           git config --global user.email "amchu1714@gmail.com"
           git commit -m "[Magic] Automated Readme update"
        
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
